library(shiny)

ui <- shinyUI(fluidPage(
  titlePanel(""),
  sidebarLayout(
    sidebarPanel(
      actionButton("add.entry","Add a New Table"),
      uiOutput("data.tables"),
      actionButton("data.type","Generate Data Tables")
    ),
    
    # Show a plot of the generated distribution
    mainPanel(
      verbatimTextOutput("make.data.tables")
    )
  )))

server <- shinyServer(function(input,output,session){
  ### Creates a value 'input.count' with value NULL.
  input.count <- NULL
  
  observeEvent(input$add.entry,{
    ### If input.count is still NULL, it indicates no new input, so the value 
    ### listed is 1.
    if (is.null(input.count)){
      input.count <<- 1
      
      ### If it isn't NULL, this indicates a value was added. Therefore, it 
      ### generates a list of values, with the ids 
    }else{
      input.count <<- c(input.count, max(input.count)+1)
    }
    output$data.tables <- renderUI({
      tagList(
        lapply(1:length(input.count), function(i){
          textInput(paste0("txtInput",input.count[i]), 
                    sprintf("Data Table #%d", input.count[i]))
        })
      )
    })
  })
  
  observeEvent(input$data.type,{
    if(is.null(input.count)){
      output$make.data.tables <- renderText({"No data tables could be generated. Please
        ensure the data you wish to insert into a table hold consistent strings
        and that you have inserted this string into the 'Data Table #' box,
        which is generated by hitting the 'Add a New Table button'. For example,
        if I have 3 CB-A samples (CB-A #1, CB-A #2, and CB-A #3), I can select 
        them all by inserting CB-A."})
    }else ({
      out <- list()
      data <- input$data_file
      ext <- tools::file_ext(data$datapath)
      req(data)
      validate(need(ext == "csv", "Please confirm uploaded file extension is saved
                  in a '.csv' format."))
      data_1 <- read.csv(data$datapath, header = input$header, check.names = FALSE)
      long_data <- pivot_longer(data_1,
                                cols = !contains('Sample'),
                                names_to = "Time_Points",
                                values_to = "Number"
      )
      ### ggplot takes many togglable options from the user 
      ### this allows the user to format the axis titles , Graph title,
      ### aixs labels, and overall color scheme. All color schemes are cupposed to be color blind friendly
      long_data_final <- rename(long_data, 'Sample' = contains('Sample'))
      back_to_wide <- pivot_wider(long_data_final,
                                  names_from = contains('Sample'),
                                  values_from = contains('Number'))
      # Get ids for textboxes
      verbatim.user.input <- sapply(1:length(input.count),function(i){
        paste("txtInput",input.count[i],sep="")
      })
      
      # Get values (put in table instructions here)
      for(i in 1:length(verbatim.user.input)){
        out[[i]] <- renderTable({
          replicates <- back_to_wide %>%
            select(contains(input[[ verbatim.user.input[i] ]]))
          average <- as.data.frame(rowMeans(replicates)) %>%
            rename(
              Average = 'rowMeans(replicates)'
            )
          all <- cbind(replicates, average)
        })
      }
      make.data.tables <- renderPrint({out})
    })
  })
})


shinyApp(ui=ui, server=server)