Homework 5
================

First load the libraries necessary for the following functions. These
are the packages “nycflights13” and “tidyverse”.

``` r
library(nycflights13)
library(tidyverse)
```

    ## Warning in as.POSIXlt.POSIXct(Sys.time()): unable to identify current timezone 'H':
    ## please set environment variable 'TZ'

The command below allows for the “visualization” the documentation of
flights.

``` r
?nycflights13::flights
```

Next, we can use the glimpse() function to view the “flights” data
frame.

``` r
glimpse(flights)
```

    ## Rows: 336,776
    ## Columns: 19
    ## $ year           <int> 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013...
    ## $ month          <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
    ## $ day            <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
    ## $ dep_time       <int> 517, 533, 542, 544, 554, 554, 555, 557, 557, 558, 55...
    ## $ sched_dep_time <int> 515, 529, 540, 545, 600, 558, 600, 600, 600, 600, 60...
    ## $ dep_delay      <dbl> 2, 4, 2, -1, -6, -4, -5, -3, -3, -2, -2, -2, -2, -2,...
    ## $ arr_time       <int> 830, 850, 923, 1004, 812, 740, 913, 709, 838, 753, 8...
    ## $ sched_arr_time <int> 819, 830, 850, 1022, 837, 728, 854, 723, 846, 745, 8...
    ## $ arr_delay      <dbl> 11, 20, 33, -18, -25, 12, 19, -14, -8, 8, -2, -3, 7,...
    ## $ carrier        <chr> "UA", "UA", "AA", "B6", "DL", "UA", "B6", "EV", "B6"...
    ## $ flight         <int> 1545, 1714, 1141, 725, 461, 1696, 507, 5708, 79, 301...
    ## $ tailnum        <chr> "N14228", "N24211", "N619AA", "N804JB", "N668DN", "N...
    ## $ origin         <chr> "EWR", "LGA", "JFK", "JFK", "LGA", "EWR", "EWR", "LG...
    ## $ dest           <chr> "IAH", "IAH", "MIA", "BQN", "ATL", "ORD", "FLL", "IA...
    ## $ air_time       <dbl> 227, 227, 160, 183, 116, 150, 158, 53, 140, 138, 149...
    ## $ distance       <dbl> 1400, 1416, 1089, 1576, 762, 719, 1065, 229, 944, 73...
    ## $ hour           <dbl> 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6...
    ## $ minute         <dbl> 15, 29, 40, 45, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59...
    ## $ time_hour      <dttm> 2013-01-01 05:00:00, 2013-01-01 05:00:00, 2013-01-0...

If we wish to see the number of total flights that were delayed by a
minimum of two hours, we can enter the command below. “120” is used as
the delayed departure time is recorded in minutes.

``` r
two_hr_late <- filter(flights, dep_delay >= 120)
print(two_hr_late)
```

    ## # A tibble: 9,888 x 19
    ##     year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
    ##    <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
    ##  1  2013     1     1      848           1835       853     1001           1950
    ##  2  2013     1     1      957            733       144     1056            853
    ##  3  2013     1     1     1114            900       134     1447           1222
    ##  4  2013     1     1     1540           1338       122     2020           1825
    ##  5  2013     1     1     1815           1325       290     2120           1542
    ##  6  2013     1     1     1842           1422       260     1958           1535
    ##  7  2013     1     1     1856           1645       131     2212           2005
    ##  8  2013     1     1     1934           1725       129     2126           1855
    ##  9  2013     1     1     1938           1703       155     2109           1823
    ## 10  2013     1     1     1942           1705       157     2124           1830
    ## # ... with 9,878 more rows, and 11 more variables: arr_delay <dbl>,
    ## #   carrier <chr>, flight <int>, tailnum <chr>, origin <chr>, dest <chr>,
    ## #   air_time <dbl>, distance <dbl>, hour <dbl>, minute <dbl>, time_hour <dttm>

This results indicates that of the original 336,776 flights, 9,888 of
them had a late departure time of at least two hours.

It may be deemed a nuisance trying to sort through both carrier
abbreviations and flight numbers, so we can combine the two via the
command below, into a new column labeled flight\_number.

``` r
flight_number <- flights %>%
  mutate(flight_number = (paste(carrier, flight)))
print(flight_number)
```

    ## # A tibble: 336,776 x 20
    ##     year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
    ##    <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
    ##  1  2013     1     1      517            515         2      830            819
    ##  2  2013     1     1      533            529         4      850            830
    ##  3  2013     1     1      542            540         2      923            850
    ##  4  2013     1     1      544            545        -1     1004           1022
    ##  5  2013     1     1      554            600        -6      812            837
    ##  6  2013     1     1      554            558        -4      740            728
    ##  7  2013     1     1      555            600        -5      913            854
    ##  8  2013     1     1      557            600        -3      709            723
    ##  9  2013     1     1      557            600        -3      838            846
    ## 10  2013     1     1      558            600        -2      753            745
    ## # ... with 336,766 more rows, and 12 more variables: arr_delay <dbl>,
    ## #   carrier <chr>, flight <int>, tailnum <chr>, origin <chr>, dest <chr>,
    ## #   air_time <dbl>, distance <dbl>, hour <dbl>, minute <dbl>, time_hour <dttm>,
    ## #   flight_number <chr>

Next, if we wanted, we can actually reorder the statement to put the
“flight\_number” column in the front. Just a personal preference.

``` r
flight_number_reordered <- summarise(flight_number, flight_number, year, month,day, dep_time, sched_dep_time, dep_delay, arr_time, sched_arr_time, arr_delay, carrier, flight, tailnum, origin, dest,air_time, distance, hour, minute, time_hour)
print(flight_number_reordered)
```

    ## # A tibble: 336,776 x 20
    ##    flight_number  year month   day dep_time sched_dep_time dep_delay arr_time
    ##    <chr>         <int> <int> <int>    <int>          <int>     <dbl>    <int>
    ##  1 UA 1545        2013     1     1      517            515         2      830
    ##  2 UA 1714        2013     1     1      533            529         4      850
    ##  3 AA 1141        2013     1     1      542            540         2      923
    ##  4 B6 725         2013     1     1      544            545        -1     1004
    ##  5 DL 461         2013     1     1      554            600        -6      812
    ##  6 UA 1696        2013     1     1      554            558        -4      740
    ##  7 B6 507         2013     1     1      555            600        -5      913
    ##  8 EV 5708        2013     1     1      557            600        -3      709
    ##  9 B6 79          2013     1     1      557            600        -3      838
    ## 10 AA 301         2013     1     1      558            600        -2      753
    ## # ... with 336,766 more rows, and 12 more variables: sched_arr_time <int>,
    ## #   arr_delay <dbl>, carrier <chr>, flight <int>, tailnum <chr>, origin <chr>,
    ## #   dest <chr>, air_time <dbl>, distance <dbl>, hour <dbl>, minute <dbl>,
    ## #   time_hour <dttm>

Lastly, we want to determine how many times each plane flew for a
certain carrier. We can do this by looking at our previous data set,
then telling the script to group the data based on the ‘tailnum’, or
plane identifier, with the ‘carrier’ they flew for. Then by summarizing
the number of times those two are found identical on the same flight, we
can have it relay that value, n(), as a variable called
‘planes.for.carrier’.

``` r
planes_for_carrier <- flight_number_reordered %>%
  group_by(tailnum, carrier) %>%
  summarise(planes.for.carrier = n(), .groups='keep')
print(planes_for_carrier)
```

    ## # A tibble: 4,067 x 3
    ## # Groups:   tailnum, carrier [4,067]
    ##    tailnum carrier planes.for.carrier
    ##    <chr>   <chr>                <int>
    ##  1 D942DN  DL                       4
    ##  2 N0EGMQ  MQ                     371
    ##  3 N10156  EV                     153
    ##  4 N102UW  US                      48
    ##  5 N103US  US                      46
    ##  6 N104UW  US                      47
    ##  7 N10575  EV                     289
    ##  8 N105UW  US                      45
    ##  9 N107US  US                      41
    ## 10 N108UW  US                      60
    ## # ... with 4,057 more rows
