library(shiny)

ui <- shinyUI(fluidPage(
  titlePanel(""),
  sidebarLayout(
    sidebarPanel(
      actionButton("add.entry","Add a New Table"),
      uiOutput("data.tables"),
      actionButton("data.type","Generate Data Tables")
    ),
    
    # Show a plot of the generated distribution
    mainPanel(
      verbatimTextOutput("make.data.tables")
    )
  )))

server <- shinyServer(function(input,output,session){
  ### Creates a value 'input.count' with value NULL.
  input.count <- NULL
  
  observeEvent(input$add.entry,{
    ### If input.count is still NULL, it indicates no new input, so the value 
    ### listed is 1.
    if (is.null(input.count)){
      input.count <<- 1
      
      ### If it isn't NULL, this indicates a value was added. Therefore, it 
      ### generates a list of values, with the ids 
    }else{
      input.count <<- c(input.count, max(input.count)+1)
    }
    output$data.tables <- renderUI({
      tagList(
        lapply(1:length(input.count), function(i){
          textInput(paste0("txtInput",input.count[i]), 
                    sprintf("Data Table #%d", input.count[i]))
        })
      )
    })
  })
  
  observeEvent(input$data.type,{
    if(is.null(input.count)){
      output$make.data.tables <- renderText({"No data tables could be generated. Please
        ensure the data you wish to insert into a table hold consistent strings
        and that you have inserted this string into the 'Data Table #' box,
        which is generated by hitting the 'Add a New Table button'. For example,
        if I have 3 CB-A samples (CB-A #1, CB-A #2, and CB-A #3), I can select 
        them all by inserting CB-A."})
    }else ({
      out <- list()
      
      ### I believe this takes the names of the inputs and puts them into a vector.
      txtbox_ids <- sapply(1:length(ids),function(i){
        paste("txtInput",ids[i],sep="")
      })
      
      ### I believe this takes the values from the pre-established values. And
      ### just add them to a textbox.
      for(i in 1:length(txtbox_ids)){
        out[[i]] <- sprintf("Txtbox #%d has value: %s",i,input[[ txtbox_ids[i] ]])
      }
      
      ### This simply takes the final version of 'out' renderPrints it into a
      ### new object and that output object is displayed later.
      output$txtOut <- renderPrint({out})
    }
  })
})


shinyApp(ui=ui, server=server)